### ISSUE TITLE
Missing omp.h on mac

### ISSUE THREAD

**Issue by PeteHaitch** [jts/nanopolish#16]
What's the proper way to fix this error? This is what I ran (OS X Yosemite 10.10.4):

```sh
$ git clone --recursive https://github.com/jts/nanopolish.git
$ make
```
_snip a bunch of output_
```sh
src/nanopolish_consensus.cpp:20:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^
1 error generated.
src/nanopolish_getmodel.cpp:21:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^
1 error generated.
src/alignment/nanopolish_eventalign.cpp:20:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^
1 error generated.
make: *** [.depend] Error 1
```

A brief google reveals this is a general problem on mac, not specific to nanopolish, but I thought you might point me in the correct direction. Please let me know if you need to see more output to help diagnose the problem.

Many thanks

**Comment by jts** [comment]
Hi Peter,

The problem is that the default compiler, clang, doesn't support openmp. To compile on OSX I install gcc-4.8 through homebrew then run:

```
make CC=gcc-4.8 CXX=g++-4.8
```

Can you give this a try?

Jared

**Comment by PeteHaitch** [comment]
Hi Jared,

Doh, I should have read the README closer. My apologies. Running:

```sh
make clean
make CC=gcc-4.8 CXX=g++-4.8
```

appears to have fixed it.

Thanks for your help.
Pete
