### ISSUE TITLE
./fast5/src/logger.hpp:224:10: error: 'function' in namespace 'std' does not name a template type

### ISSUE THREAD

**Issue by mmokrejs** [jts/nanopolish#146]
Hi,
  with current git master I get:

```
 CFLAGS="-O2 -pipe -march=native -ftree-vectorize" CXXFLAGS="-O2 -pipe -march=native -ftree-vectorize" make HDF5=noinstall
g++ -o src/nanopolish_getmodel.o -c -O2 -pipe -march=native -ftree-vectorize -std=c++11 -fopenmp  -I./htslib -I./fast5/src -I./src -I./src/hmm -I./src/thirdparty -I./src/common -I./src/alignment -fPIC src/nanopolish_getmodel.cpp
In file included from ./fast5/src/fast5.hpp:25:0,
                 from src/nanopolish_getmodel.cpp:23:
./fast5/src/logger.hpp:224:10: error: 'function' in namespace 'std' does not name a template type
     std::function<void()> _on_destruct;
          ^~~~~~~~
./fast5/src/logger.hpp: In constructor 'logger::Logger::Logger(const string&, logger::level, const string&, unsigned int, const string&, std::ostream&)':
./fast5/src/logger.hpp:101:9: error: '_on_destruct' was not declared in this scope
         _on_destruct = [&] () {
         ^~~~~~~~~~~~
./fast5/src/logger.hpp:101:9: note: suggested alternative: '__locale_struct'
         _on_destruct = [&] () {
         ^~~~~~~~~~~~
         __locale_struct
./fast5/src/logger.hpp: In constructor 'logger::Logger::Logger(int, const string&, unsigned int, const string&, std::ostream&)':
./fast5/src/logger.hpp:112:9: error: '_on_destruct' was not declared in this scope
         _on_destruct = [&] () {
         ^~~~~~~~~~~~
./fast5/src/logger.hpp:112:9: note: suggested alternative: '__locale_struct'
         _on_destruct = [&] () {
         ^~~~~~~~~~~~
         __locale_struct
./fast5/src/logger.hpp: In constructor 'logger::Logger::Logger(const Exception&, const string&, unsigned int, const string&, typename std::enable_if<std::is_base_of<std::exception, Exception>::value>::type*)':
./fast5/src/logger.hpp:132:9: error: '_on_destruct' was not declared in this scope
         _on_destruct = [&] () {
         ^~~~~~~~~~~~
./fast5/src/logger.hpp:132:9: note: suggested alternative: '__locale_struct'
         _on_destruct = [&] () {
         ^~~~~~~~~~~~
         __locale_struct
./fast5/src/logger.hpp: In destructor 'logger::Logger::~Logger()':
./fast5/src/logger.hpp:139:9: error: '_on_destruct' was not declared in this scope
         _on_destruct();
         ^~~~~~~~~~~~
./fast5/src/logger.hpp:139:9: note: suggested alternative: '__locale_struct'
         _on_destruct();
         ^~~~~~~~~~~~
         __locale_struct
make: *** [Makefile:104: src/nanopolish_getmodel.o] Error 1
```

**Comment by jts** [comment]
This is probably a GCC version issue, nanopolish requires gcc 4.8 or greater.

**Comment by mmokrejs** [comment]
I forgot to add, I tried 4.9.4 and 7.1.0, also I thing 6.2.0. Provided my server has hdf5-1.8.18 I assume it is either fixed in nver version or there is a patch floating around.

**Comment by eyasi** [comment]
Hi - I think I'm getting a similar GCC issue and haven't been able to fix it. Any more ideas?

`src/nanopolish_call_variants.cpp:418:75: error: call of overloaded ‘abs(unsigned int)’ is ambiguous
         double num_events = abs(data.event_start_idx - data.event_stop_idx) + 1;
                                                                           ^
In file included from /usr/local/Cellar/gcc/7.1.0/include/c++/7.1.0/cstdlib:75:,
                 from /usr/local/Cellar/gcc/7.1.0/include/c++/7.1.0/stdlib.h:36,
                 from src/nanopolish_call_variants.cpp:9:
/usr/include/stdlib.h:129:6: note: candidate: int abs(int)
 int  abs(int) __pure2;
      ^~~`

**Comment by jts** [comment]
Hi,

This is a different issue. I suggest however that you compile using gcc-4.8 or 4.9 for now until I make nanopolish compatible with gcc 7.x.

Jared
